### ISSUE TITLE
Documentation updating/packaging

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/docs#6]
As mentioned by @frostmakk in https://github.com/ForumPostAssistant/FPA/issues/90 and, separately by me in https://github.com/ForumPostAssistant/FPA/issues/91

(1) The documentation is incomplete (but it's probably good enough for most people to use)
(2) The "first time user's guide" .pdf becomes obsolete with the new UX

In relation to point (2) above, is the .pdf file necessary and should it be bundled with the package?  I have no particular view on this but, perhaps in the rare case that someone downloads the FPA, has no access to the internet (to see the online doco) the .pdf guide could be useful if working offline.

I say it "could be useful" if it was up-to-date with screenshots (which it's not).

It's a fair bit of work to rewrite the .pdf guide and I wouldn't propose investing my time in doing it if it's only useful once in every hundred times.

Questions:

- [ ] Decide to retain the .pdf file, rewrite it, and include it with the download

- [ ] Decide to remove the .pdf file and eliminate the "/Documentation" folder entirely from the distro

- [ ] Complete the incomplete areas of the online doco and how that can be done.

Updating the online doco is kind of "technical" ==> GitHub-specific skills (that I don't currently possess); it's a fair amount of work and I don't want to burden @RussW who's done a fantastic job getting things to where they are today.

For comment/resolution, please.

**Comment by mandville** [comment]
i would opt for this one Decide to remove the .pdf file and eliminate the "/Documentation" folder entirely from the distro 
if the fpa is deleted people would probably expect the docs to be deleted also#

**Comment by sozzled** [comment]
@mandville wrote
> if the fpa is deleted people would probably expect the docs to be deleted also

I don't think so or, the /Documentation folder is only deleted from an extracted copy of the downloaded .zip/.tar.gz that they may be using.  I'll catch up again after [my] lunchtime.

**Comment by RussW** [comment]
Please find a new branch named "**1.6.0-Update**"

- converted pages from jekyll to html for simpler maintenance by all parties

- updated _"Quick Start Guide"_ steps, now has 8 steps to clarify some items

- updated some _"Administrator Guide"_ sections for 1.6.0

- added "Advanced Function" information in _Administrator Guide_ for completeness and transparency of settings constants

**Comment by RussW** [comment]
All documentation has been updated for v1.6.0 and all sections now have content and images in the "Administrator Guide" page.

Please review, otherwise, I guess tis is ready to go along with the FPA v1.6.0 release.

**Comment by frostmakk** [comment]
In administrator guide this section with mention of privacy settings:
![image](https://user-images.githubusercontent.com/25645600/84694562-b0afb500-af49-11ea-9d62-3de3d0c3c731.png)
Contradicts this mentioned a bit earlier on the page.
![image](https://user-images.githubusercontent.com/25645600/84694784-0c7a3e00-af4a-11ea-9805-fab1ea527c22.png)

************************************************
I believe there should be mentioned in both guides that the user should preview the post before sending, and if necessary sanitize PHP error messages.

************************************************

It feels a little unbalanced with these two sentences 2 inches from each other.
One quite laid back, and the other a bit over the top?

![image](https://user-images.githubusercontent.com/25645600/84696662-249f8c80-af4d-11ea-9de2-dc4369fc98fa.png)


![image](https://user-images.githubusercontent.com/25645600/84696763-41d45b00-af4d-11ea-8de4-3912f9c7a4e3.png)

**Comment by RussW** [comment]
Well caught, sir!
Have removed mention of the privacy setting in that note as it is no-longer applicable.
